@startuml UC07_api_backend
!pragma layout smetana
skinparam shadowing false
skinparam defaultFontSize 11
skinparam backgroundColor white
skinparam ArrowColor #333333
skinparam ArrowThickness 1
skinparam Padding 5
skinparam actorStyle none
skinparam usecase {
  BackgroundColor white
  BorderColor #666666
}
skinparam actor {
  BackgroundColor white
  BorderColor #333333
}
skinparam rectangle {
  BackgroundColor #F8F8F8
  BorderColor #AAAAAA
}

title UC07 - Backend API Spring Boot 3.3 / Java 21\nGestion contrats et dossiers credit

left to right direction

actor "Angular (Web)" as ANG <<systeme>>
actor "Flutter (Mobile)" as FLT <<systeme>>
actor "Agent de Saisie\n(AGENT_SAISIE)" as SAI
actor "PostgreSQL 15" as PG <<systeme>>

rectangle "UC07 - Backend API Spring Boot" {

  usecase "UC07.1\nAuthentifier une requete\n(validation cookie imf_access)" as UC0701
  usecase "UC07.2\nAutoriser par role\n(RBAC Spring Security)" as UC0702
  usecase "UC07.3\nExposer KPIs\n(PAR, collectes, recouvrement)" as UC0703
  usecase "UC07.4\nEnregistrer collecte\nterrain (POST)" as UC0704
  usecase "UC07.5\nGerer alertes\n(liste, cloture, escalade)" as UC0705
  usecase "UC07.6\nGerer dossiers credit\net contrats" as UC0706
  usecase "UC07.7\nGerer utilisateurs\n(CRUD + roles)" as UC0707
  usecase "UC07.8\nLoguer chaque\nappel API (audit trail)" as UC0708
  usecase "UC07.9\nExposer doc\nAPI Swagger (OpenAPI 3.0)" as UC0709
  usecase "UC07.10\nServir stream SSE\n(notifications web temps reel)" as UC0710

}

ANG --> UC0701
ANG --> UC0703
ANG --> UC0705
ANG --> UC0706
ANG --> UC0710
FLT --> UC0701
FLT --> UC0703
FLT --> UC0704
SAI --> UC0706

PG  --> UC0703
UC0704 --> PG
UC0706 --> PG

UC0701 ..> UC0702 : <<include>>
UC0703 ..> UC0701 : <<include>>
UC0704 ..> UC0701 : <<include>>
UC0705 ..> UC0701 : <<include>>
UC0706 ..> UC0701 : <<include>>
UC0703 ..> UC0708 : <<include>>
UC0704 ..> UC0708 : <<include>>

@enduml
